version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "dc/eventy-server"
    ports:
      - "3001:3001"
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image:"dc/eventy-client"
    ports:
      -"3000:3000"
