version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    image: "n10324321/eventy-server"
    ports:
      - "3001:3001"
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image:"n10324321/eventy-client"
    ports:
      -"3000:3000"
